# Generated by Django 2.2.4 on 2022-09-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='num_of_ninjas',
            field=models.IntegerField(default=0),
        ),
    ]
